name: chuck_norris_facts
description: Chuck Norris facts app.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  chopper: ^4.0.4
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^1.0.3
  json_annotation: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.1.7
  chopper_generator: ^4.0.3
  flutter_lints: ^1.0.4
  json_serializable: ^6.1.3
  mockito: ^5.0.16

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true
